"""
math_engine.synthetic
---------------------
Physically-consistent synthetic mature gas wells, generated BY the engine
itself, so backtests have a ground-truth death month without field data.

Recipe per well (seeded RNG -> reproducible):
    1. Draw completion/fluid parameters (depth, ID, water, gravities).
    2. Draw an R-S IPR (AOF 3-9 MMscf/D, n 0.75-1.0).
    3. Pick initial pressure Pi and OGIP G; p/z line follows volumetric MB.
    4. March monthly: solve the natural flow point at current Pr with the
       BB VLP; stop when the well cannot flow or Turner flags loading
       (same criterion as forecast_well_life) -> truth_death_day.

Units: field units (CONTEXT.md).
"""

import random
from typing import Dict, List, Optional

from math_engine.backtest import DAYS_PER_MONTH, _vlp_from_params
from math_engine.forecast import pressure_at_cumulative, pz_from_p
from math_engine.liquid_loading import loading_assessment
from math_engine.metastable import metastable_extended_life
from math_engine.nodal_analysis import find_natural_flow_point
from math_engine.nodal_helpers import build_rawlins_schellhardt_ipr_func


def make_mature_gas_well(seed: int = 0, months: int = 30,
                         time_step_days: float = DAYS_PER_MONTH,
                         econ_limit_mscfd: float = 20.0) -> Dict:
    """Generate one synthetic well with full monthly history + truth."""
    rng = random.Random(seed)

    params = {
        "p_wh": round(rng.uniform(100.0, 300.0), 1),
        "t_wh_f": round(rng.uniform(80.0, 110.0), 1),
        "t_res_f": round(rng.uniform(150.0, 200.0), 1),
        "tvd_ft": round(rng.uniform(6000.0, 9000.0), 0),
        "tubing_id_in": rng.choice([1.75, 1.995, 1.995]),
        "gamma_g": round(rng.uniform(0.60, 0.72), 3),
        "q_water_bpd": round(rng.uniform(60.0, 200.0), 1),
        "liquid_sg": 1.0,
        "vlp_model": "beggs_brill",
        "load_method": "turner",
        "friction_multiplier": 1.0,
        "q_gas_nominal_mscfd": 800.0,
    }
    t_res = params["t_res_f"] + 460.0
    gg = params["gamma_g"]
    d = params["tubing_id_in"]

    # Rawlins-Schellhardt IPR - mature well: modest absolute open flow.
    aof = rng.uniform(400.0, 1600.0)
    n_exp = round(rng.uniform(0.75, 1.0), 3)
    Pi = round(rng.uniform(1200.0, 2600.0), 0)
    C = aof / (Pi ** (2.0 * n_exp))
    params["ipr"] = ("rs", {"C": C, "n": n_exp})

    # Volumetric material balance line: P/Z = (Pi/Z)(1 - Gp/G)
    G = round(rng.uniform(2500.0, 9000.0), 0)  # MMscf
    intercept = pz_from_p(Pi, t_res, gg)
    slope = -intercept / G

    vlp = _vlp_from_params(params)
    q_min_scan = max(params["q_gas_nominal_mscfd"] / 100.0, 5.0)

    Gp = round(rng.uniform(200.0, 800.0), 1)
    rows: List[Dict] = []
    truth_death_day: Optional[float] = None

    for month in range(1, months + 1):
        Pr = pressure_at_cumulative(Gp, intercept, slope, t_res, gg)
        if Pr < 200.0:  # essentially depleted
            truth_death_day = (month - 0.5) * time_step_days
            break

        ipr = build_rawlins_schellhardt_ipr_func(Pr, C, n_exp)
        flow = find_natural_flow_point(ipr, vlp, q_min=q_min_scan,
                                       q_max=aof * 1.05, n_scan=50,
                                       prefer="highest_rate")
        if flow is None:
            truth_death_day = (month - 0.5) * time_step_days
            break
        q_op = flow["q_mscfd"]
        pwf_op = flow["Pwf_psia"]

        loading = bool(loading_assessment(
            pwf_op, t_res, gg, d, q_op,
            method=params["load_method"])["is_loading"])
        if loading:
            la_detail = loading_assessment(
                pwf_op, t_res, gg, d, q_op,
                method=params["load_method"])
            meta = metastable_extended_life(
                la_detail["q_crit_mscfd"], q_op, liquid_type="water")
            if not meta["can_flow"]:
                rows.append({"month": month, "Gp_mmscf": Gp, "P_psia": Pr,
                             "q_gas_mscfd": q_op, "Pwf_psia": pwf_op,
                             "is_loading": True})
                truth_death_day = (month - 0.5) * time_step_days
                break
            else:
                rows.append({"month": month, "Gp_mmscf": Gp, "P_psia": Pr,
                             "q_gas_mscfd": q_op, "Pwf_psia": pwf_op,
                             "is_loading": False})
                Gp += q_op * time_step_days / 1000.0
        elif q_op < econ_limit_mscfd:
            rows.append({"month": month, "Gp_mmscf": Gp, "P_psia": Pr,
                         "q_gas_mscfd": q_op, "Pwf_psia": pwf_op,
                         "is_loading": True})
            truth_death_day = (month - 0.5) * time_step_days
            break
        else:
            rows.append({"month": month, "Gp_mmscf": Gp, "P_psia": Pr,
                         "q_gas_mscfd": q_op, "Pwf_psia": pwf_op,
                         "is_loading": False})
            Gp += q_op * time_step_days / 1000.0

    if truth_death_day is None:  # survived the whole window
        truth_death_day = (months + 0.5) * time_step_days

    return {
        "params": params,
        "rows": rows,
        "gp_list": [r["Gp_mmscf"] for r in rows],
        "p_list": [r["P_psia"] for r in rows],
        "truth_death_day": truth_death_day,
        "ogip_mmscf": G,
        "aof_mscfd": aof,
    }
