"""production records measured pwf

Revision ID: 02b639a0b9ad
Revises: 72767c5b23bd
Create Date: 2026-08-22 18:12:30.432718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02b639a0b9ad'
down_revision: Union[str, None] = '72767c5b23bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pwf_psia', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_records', schema=None) as batch_op:
        batch_op.drop_column('pwf_psia')

    # ### end Alembic commands ###
