"""oil wells: well_type + oil_api

Revision ID: 6f3cb4ae9f25
Revises: 02b639a0b9ad
Create Date: 2026-08-22 18:47:55.777850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f3cb4ae9f25'
down_revision: Union[str, None] = '02b639a0b9ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wells', schema=None) as batch_op:
        batch_op.add_column(sa.Column('well_type', sa.String(length=8), server_default='gas', nullable=False))
        batch_op.add_column(sa.Column('oil_api', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wells', schema=None) as batch_op:
        batch_op.drop_column('oil_api')
        batch_op.drop_column('well_type')

    # ### end Alembic commands ###
