"""well friction multiplier calibration

Revision ID: 72767c5b23bd
Revises: 7bed8244f11b
Create Date: 2026-08-22 15:54:01.742031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72767c5b23bd'
down_revision: Union[str, None] = '7bed8244f11b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wells', schema=None) as batch_op:
        batch_op.add_column(sa.Column('friction_multiplier', sa.Float(), server_default='1.0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wells', schema=None) as batch_op:
        batch_op.drop_column('friction_multiplier')

    # ### end Alembic commands ###
