"""auth api keys and well ownership

Revision ID: 7bed8244f11b
Revises: 9f94acd98a11
Create Date: 2026-08-22 15:37:18.880979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bed8244f11b'
down_revision: Union[str, None] = '9f94acd98a11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('field_name', sa.String(length=128), nullable=True),
    sa.Column('tier', sa.String(length=8), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.add_column('wells', sa.Column('owner_key_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_wells_owner_key_id'), 'wells', ['owner_key_id'], unique=False)
    op.create_foreign_key(None, 'wells', 'api_keys', ['owner_key_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wells', type_='foreignkey')
    op.drop_index(op.f('ix_wells_owner_key_id'), table_name='wells')
    op.drop_column('wells', 'owner_key_id')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
