"""initial schema

Revision ID: 9f94acd98a11
Revises: 
Create Date: 2026-08-22 15:17:28.561196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f94acd98a11'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wells',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('p_res', sa.Float(), nullable=False),
    sa.Column('t_res_f', sa.Float(), nullable=False),
    sa.Column('gamma_g', sa.Float(), nullable=False),
    sa.Column('p_wh', sa.Float(), nullable=False),
    sa.Column('t_wh_f', sa.Float(), nullable=False),
    sa.Column('tvd_ft', sa.Float(), nullable=False),
    sa.Column('tubing_id_in', sa.Float(), nullable=False),
    sa.Column('q_water_bpd', sa.Float(), nullable=False),
    sa.Column('liquid_sg', sa.Float(), nullable=False),
    sa.Column('q_gas_nominal_mscfd', sa.Float(), nullable=False),
    sa.Column('vlp_model', sa.String(length=32), nullable=False),
    sa.Column('load_method', sa.String(length=16), nullable=False),
    sa.Column('a_coef', sa.Float(), nullable=True),
    sa.Column('b_coef', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wells_tag'), 'wells', ['tag'], unique=True)
    op.create_table('deliverability_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('well_id', sa.Integer(), nullable=False),
    sa.Column('points', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['well_id'], ['wells.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deliverability_tests_well_id'), 'deliverability_tests', ['well_id'], unique=True)
    op.create_table('production_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('well_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('q_gas_mscfd', sa.Float(), nullable=False),
    sa.Column('q_water_bpd', sa.Float(), nullable=True),
    sa.Column('p_wh_psia', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['well_id'], ['wells.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_records_well_id'), 'production_records', ['well_id'], unique=False)
    op.create_table('scada_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('well_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=True),
    sa.Column('q_gas_mscfd', sa.Float(), nullable=False),
    sa.Column('q_water_bpd', sa.Float(), nullable=True),
    sa.Column('p_wh_psia', sa.Float(), nullable=True),
    sa.Column('is_loading', sa.Boolean(), nullable=False),
    sa.Column('margin_fraction', sa.Float(), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['well_id'], ['wells.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scada_readings_ts'), 'scada_readings', ['ts'], unique=False)
    op.create_index(op.f('ix_scada_readings_well_id'), 'scada_readings', ['well_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scada_readings_well_id'), table_name='scada_readings')
    op.drop_index(op.f('ix_scada_readings_ts'), table_name='scada_readings')
    op.drop_table('scada_readings')
    op.drop_index(op.f('ix_production_records_well_id'), table_name='production_records')
    op.drop_table('production_records')
    op.drop_index(op.f('ix_deliverability_tests_well_id'), table_name='deliverability_tests')
    op.drop_table('deliverability_tests')
    op.drop_index(op.f('ix_wells_tag'), table_name='wells')
    op.drop_table('wells')
    # ### end Alembic commands ###
