"""Backtest the liquid-loading death forecast.

Synthetic mode (no field data needed - wells generated BY the engine,
so ground truth is exact):

    python scripts/backtest.py --seeds 0 3 11
    python scripts/backtest.py --seeds 0-9 --months 36

CSV mode (your own p/z history: header with Gp and P columns):

    python scripts/backtest.py --csv history.csv --params well_params.json

Metrics per well: MAE (months) of predicted death day across
walk-forward cutoffs + hit-rate within +/- tol months of truth.
"""

import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from math_engine.backtest import (DAYS_PER_MONTH, score_predictions,  # noqa: E402
                                  walk_forward)
from math_engine.synthetic import make_mature_gas_well  # noqa: E402


def _expand_seeds(token):
    if "-" in token:
        lo, hi = token.split("-")
        return list(range(int(lo), int(hi) + 1))
    return [int(token)]


def run_synthetic(seeds, months, min_fit, step, tol):
    print("Walk-forward backtest vs synthetic truth "
          "(min_fit={} step={} tol={:.0f}m)".format(min_fit, step, tol))
    maes, hits = [], []
    for s in seeds:
        w = make_mature_gas_well(seed=s, months=months)
        if len(w["rows"]) < max(min_fit, 3):
            print("seed {:>2}: only {} rows before death - skipped"
                  .format(s, len(w["rows"])))
            continue
        preds = walk_forward(w["params"], w["gp_list"], w["p_list"],
                             min_fit=min_fit, step=step)
        sc = score_predictions(preds, w["truth_death_day"], tol_months=tol)
        if sc["n_preds"] == 0:
            print("seed {:>2}: no valid predictions".format(s))
            continue
        print("seed {:>2}: rows={:>2} truth={:>6.1f}d | MAE={:5.2f}m "
              "hit(+/-{:.0f}m)={:5.1f}%"
              .format(s, len(w["rows"]), w["truth_death_day"],
                      sc["mae_months"], tol, sc["hit_rate"] * 100.0))
        maes.append(sc["mae_months"])
        hits.append(sc["hit_rate"])
    if maes:
        print("-" * 52)
        print("AGGREGATE over {} wells: MAE={:.2f} months | "
              "mean hit-rate={:.1f}%"
              .format(len(maes), sum(maes) / len(maes),
                      sum(hits) / len(hits) * 100.0))


def run_csv(path, min_fit, step, tol):
    import csv

    from math_engine.backtest import predict_death_day
    with open(path, newline="", encoding="utf-8-sig") as fh:
        reader = csv.DictReader(fh)
        cols = {c.strip().lower(): c for c in reader.fieldnames or []}
        gp_col = cols.get("gp") or cols.get("gp_mmscf")
        p_col = cols.get("p") or cols.get("p_psia")
        if not gp_col or not p_col:
            sys.exit("CSV needs Gp and P columns")
        gp = [float(r[gp_col]) for r in reader]
    # re-read for P (DictReader consumed); simple second pass
    with open(path, newline="", encoding="utf-8-sig") as fh:
        reader = csv.DictReader(fh)
        cols = {c.strip().lower(): c for c in reader.fieldnames}
        p = [float(r[cols.get("p") or cols.get("p_psia")]) for r in reader]

    params = {
        "p_wh": 200.0, "t_wh_f": 100.0, "t_res_f": 170.0,
        "tvd_ft": 8000.0, "tubing_id_in": 1.995,
        "gamma_g": 0.65, "q_water_bpd": 30.0, "liquid_sg": 1.0,
        "vlp_model": "beggs_brill", "load_method": "turner",
    }
    rel, hist = predict_death_day(params, gp[:8], p[:8])
    label = ("dies in ~{:.0f} days from cutoff"
             .format(rel) if rel is not None else "no death within horizon")
    print("First-cutoff forecast (first 8 points): {}".format(label))


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--seeds", nargs="*", default=["0", "3", "11"],
                    help="seeds or ranges like 0-9 (synthetic mode)")
    ap.add_argument("--months", type=int, default=30)
    ap.add_argument("--csv", default=None,
                    help="history CSV with Gp,P columns instead of synthetic")
    ap.add_argument("--min-fit", type=int, default=8)
    ap.add_argument("--step", type=int, default=2)
    ap.add_argument("--tol-months", type=float, default=2.0)
    args = ap.parse_args()

    if args.csv:
        run_csv(args.csv, args.min_fit, args.step, args.tol_months)
    else:
        seeds = []
        for tok in args.seeds:
            seeds.extend(_expand_seeds(tok))
        run_synthetic(seeds, args.months, args.min_fit, args.step,
                      args.tol_months)


if __name__ == "__main__":
    main()
